Document: zenstates
Title: Debian zenstates Manual
Author: <insert document author here>
Abstract: This manual describes what zenstates is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zenstates/zenstates.sgml.gz

Format: postscript
Files: /usr/share/doc/zenstates/zenstates.ps.gz

Format: text
Files: /usr/share/doc/zenstates/zenstates.text.gz

Format: HTML
Index: /usr/share/doc/zenstates/html/index.html
Files: /usr/share/doc/zenstates/html/*.html
